export const APPWRITE_ENDPOINT = process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT;
export const APPWRITE_PROJECT = process.env.EXPO_PUBLIC_APPWRITE_PROJECT;
export const APPWRITE_PLATFORM = process.env.EXPO_PUBLIC_APPWRITE_PLATFORM;
